### ISSUE TITLE
We need change icon on empty state to tables and charts, icon distinct to tooltip icon

### ISSUE THREAD

**Issue by AngeloCG97** [defactor-com/ui-kit#181]
- [x] Define new icon @Edwinjrc
- [x] Add as default icon on this empty states @JAMares

**Comment by Edwinjrc** [comment]
Also notice a few changes to the texts styles in this component.

![Image](https://github.com/defactor-com/ui-kit/assets/106584978/3dd05e13-5513-4063-a1c1-b32ffec86617)
