### ISSUE TITLE
Add MUI Themes to UI-Kit Storybook

### ISSUE THREAD

**Issue by xavier506** [defactor-com/ui-kit#270]
There is a MUI plugin that automatically adds the MUI themes to story book , this can save us time setting default styles for each component 

- [x] Pre load MUI theme in all components on storybook 
- [x] Configuring controls (colors , borders, varients) - load from this library: https://storybook.js.org/recipes/@mui/material

**Comment by pzagardedukic** [comment]
yarn add next@latest typescript@latest @types/react@latest @types/node@latest yarn add @storybook/react @storybook/addon-essentials @storybook/addon-controls @mui/material @emotion/react @emotion/styled
