### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by AngeloCG97** [defactor-com/ui-kit#29]
![Image](https://github.com/defactor-com/ui-kit/assets/5632966/613f2775-9baa-493c-89ba-5da9512696aa)

![Image](https://github.com/defactor-com/ui-kit/assets/5632966/b75ae376-0359-4d50-8b1b-0c740ccb8bfd)

![Image](https://github.com/defactor-com/ui-kit/assets/5632966/584dfd2b-3f19-4792-a1f1-3686a3d11dcb)

**Comment by xavier506** [comment]
we will create a general component with UI development , seperate specific issues can be mode for detailed functionality one the first version of the component
