### ISSUE TITLE
Implement Change Indicator on Frontend

### ISSUE THREAD

**Issue by xavier506** [defactor-com/ui-kit#64]
The chnage indicator is based on the last 24 hour trend 

however we dont have the historical information available in the backend right now . 

![Image](https://github.com/defactor-com/ui-kit/assets/5632966/e61f1933-7077-4322-b371-9baee7222324)

![Image](https://github.com/defactor-com/ui-kit/assets/5632966/7de2e3ba-18c5-4b92-aacf-2af0d86d7da7)

**Comment by leisterfrancisco** [comment]
@xavier506 @AngeloCG97 is it still relevant?

**Comment by AngeloCG97** [comment]
I don't think it's valuable

**Comment by leisterfrancisco** [comment]
Not relevant at this point
