### ISSUE TITLE
Improve Balance Display

### ISSUE THREAD

**Issue by xavier506** [defactor-com/ui-kit#77]
I dont think they should be stacked.  Better to display as 1,000 USDC in one line

![Image](https://github.com/defactor-com/ui-kit/assets/5632966/1d94d053-a298-40fe-bc6e-23cf7fb050e2)

**Comment by Edwinjrc** [comment]
![Image](https://github.com/defactor-com/ui-kit/assets/106584978/5fd1af7b-9f6e-4fd4-b352-7f67f4b3573a)
